### ISSUE TITLE
pyvideo.search returns 404 links whenever there's an '@' or ':' in the name

### ISSUE THREAD

**Issue by abhiramr** [pyvideo/pyvideo#159] opened 2018-08-26 19:39 UTC
E.g. Search link  - https://pyvideo.org/search.html?q=django

E.g result on Search page - "Carl Meyer about Django @ Instagram at Django: Under The Hood 2016"
**Associated URL in search page -**

>  /django-under-the-hood-2016/carl-meyer-about-django-at-instagram-at-django-under-the-hood-2016.html (Notice the extra 'at')

**Actual JSON file and consequently html -** 

>  /django-under-the-hood-2016/carl-meyer-about-django-instagram-at-django-under-the-hood-2016.html  

The "hit.fields.url " gets populated by substituting '@' as 'at' and ':' as '-'. If these links don't match the ones in the JSON files, the returned pages are understandably 404s.
They should ideally be picked from the JSON files associated with the results.

**Comment by zerok** [comment] 2018-10-25 17:37
Sorry for taking so long 🙁  I will try to hotfix this ASAP. Just haven't looked at the code in a long time ^_^

**Comment by abhiramr** [comment] 2018-10-25 17:45
I'm happy it's being looked into at all! :) I tried to check it out myself but got busy and dropped it :(

**Comment by zerok** [comment] 2018-10-25 17:48
Ah, the problem is actually that the library I'm using to generate the slug for the URL produces a different output for special characters than pelican.utils.slugify. I guess it is time to re-implement that helper in Go ^_^

**Comment by zerok** [comment] 2018-10-25 18:51
Fixed with https://github.com/zerok/pyvideosearch/commit/6ebcbd1b78434d052055d6f9362ab731ec27fa4f 🙂  The fix is also deployed and the search page.

**Closed as completed by zerok** 2018-10-25 18:51 UTC

**Comment by abhiramr** [comment] 2018-10-26 05:11
Verified on the search page as well ! :) Thank you! ^_^
